// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHfR3y-XHl3IPOOfg25KGMEyfFiGiQPKg',
    appId: '1:121891115216:web:747d154bd48f1a2d130ed5',
    messagingSenderId: '121891115216',
    projectId: 'mybookstash-9ef61',
    authDomain: 'mybookstash-9ef61.firebaseapp.com',
    storageBucket: 'mybookstash-9ef61.firebasestorage.app',
    measurementId: 'G-44KCQSW10K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYbz3r_D3hRZOtjJpvRCMyCaH8YkSFFxY',
    appId: '1:121891115216:android:dc57542554c55a10130ed5',
    messagingSenderId: '121891115216',
    projectId: 'mybookstash-9ef61',
    storageBucket: 'mybookstash-9ef61.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHSassmpjaJxUOZcVbtY4TT0efWx4-wHA',
    appId: '1:121891115216:ios:66e8e79bb71cf06c130ed5',
    messagingSenderId: '121891115216',
    projectId: 'mybookstash-9ef61',
    storageBucket: 'mybookstash-9ef61.firebasestorage.app',
    iosBundleId: 'com.example.bookStashNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHSassmpjaJxUOZcVbtY4TT0efWx4-wHA',
    appId: '1:121891115216:ios:66e8e79bb71cf06c130ed5',
    messagingSenderId: '121891115216',
    projectId: 'mybookstash-9ef61',
    storageBucket: 'mybookstash-9ef61.firebasestorage.app',
    iosBundleId: 'com.example.bookStashNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHfR3y-XHl3IPOOfg25KGMEyfFiGiQPKg',
    appId: '1:121891115216:web:9fc951957f1b768b130ed5',
    messagingSenderId: '121891115216',
    projectId: 'mybookstash-9ef61',
    authDomain: 'mybookstash-9ef61.firebaseapp.com',
    storageBucket: 'mybookstash-9ef61.firebasestorage.app',
    measurementId: 'G-7MFME76P79',
  );
}